### ISSUE TITLE
Other challenges

### ISSUE THREAD

**Issue by mik8142** [dhammon/ai-goat#4]
Hello! First of all, thanks for your great work!

Should I expect the rest of the Challenges in the foreseeable future?

**Comment by dhammon** [comment]
I'm constantly finding more urgent things to do!  But I hope to pick this one up again in a few months (no promises).  Thank you for the interest in the repo!

**Comment by nlahmi** [comment]
Just finished both challenges, they are great, and so is the entire platform
I really hope you can have the time to add more, and thank you for your work!
