### ISSUE TITLE
check model if exists 

### ISSUE THREAD

**Issue by hu-guanwei** [dhammon/ai-goat#6]
Hi!

I think the code only checks if the file ggml-old-vic13b-q4_0.bin exists, but without data integrity check. My first  download failed, I cannot start the container before manually remove the partial model file and download it again. Maybe add a md5sum check and relevant error message?

**Comment by dhammon** [comment]
Good suggestion, although I'm not sure if I'd get around to that.  Feel free to contribute.  Thanks for the interest in ai-goat!

**Comment by dhammon** [comment]
Well done and merged.  Thanks @hu-guanwei !
