### ISSUE TITLE
change the flag

### ISSUE THREAD

**Issue by havertz2110** [dhammon/ai-goat#9]
hello, what if i want to change the flag on ctfd, how can i do it

**Comment by dhammon** [comment]
@havertz2110 thanks for the interest.  You can change the flags within the challenges source code and then in CFTD (they must match).  

1. After you clone the repo, navigate to ai-goat/app/challenges/1/app.py and change the flag in the string on line 12.  
2. Then navigate to ai-goat/app/challenges/2/entrypoint.sh and change the flag on line 3.  
3. Next you will need to change the flags in CFTD.  Launch CFTD and then login with the root user using qVLv27Dsy5WuXRubjfII as the password.  
4. Once logged in, navigate the admin panel (top nav bar) -> Challenges (top nav bar) -> select a challenge -> and hit the Flags sub-tab.  
5. Change the flag for each CFTD challenge to match the same string you changed the in the source code.

Have fun!

**Comment by havertz2110** [comment]
Thank you so much for your dedicated and helpful answer :D
